#!/bin/bash
#################### 3x-ui-pro — subscription duplicator (x-ui-sub-dub.sh) #####
#
# Duplicate (дюп) a remote subscription as a static copy served from this
# panel server, so your clients fetch it from here — the provider's
# per-device limits stop applying because only this server talks to it.
#
# Usage (run ON the panel server):
#   bash x-ui-sub-dub.sh -url "https://sub.provider.example/abc" -name alvsub [-interval 4]
#   bash x-ui-sub-dub.sh -list
#   bash x-ui-sub-dub.sh -remove alvsub
#
#   -url        the remote subscription URL (raw share links, base64 or JSON)
#   -name       short label used for the cron/scripts and identification
#   -interval   refresh period in hours (default 4)
#
# What it does: fetches the remote sub with a VPN-client User-Agent (many
# providers 502 plain browsers), validates the content, saves it under a
# random secret path in the web root and sets up a cron that refreshes it.
# The public URL is printed and stored in /etc/x-ui/3x-ui-pro/subs/.
#
# WARNING: educational purposes only. Duplicating a subscription you do not
# own may violate the provider's terms — you are responsible for your use.
#
[[ $EUID -ne 0 ]] && { echo "Run as root: sudo bash $0"; exit 1; }

msg_ok()  { echo -e "\e[1;42m $1 \e[0m"; }
msg_err() { echo -e "\e[1;41m $1 \e[0m"; }
msg_inf() { echo -e "\e[1;34m$1\e[0m"; }

STATE_FILE="/etc/x-ui/3x-ui-pro/install.env"
SUBS_DIR="/etc/x-ui/3x-ui-pro/subs"
WEB_ROOT="/var/www/html"
[[ -f "$STATE_FILE" ]] && source "$STATE_FILE"
DOMAIN="${DOMAIN:-$(hostname -f)}"

URL=""
NAME=""
INTERVAL="4"
MODE="add"

while [[ $# -gt 0 ]]; do
    case "$1" in
        -url)      URL="$2";      shift 2 ;;
        -name)     NAME="$2";     shift 2 ;;
        -interval) INTERVAL="$2"; shift 2 ;;
        -list)     MODE="list";   shift ;;
        -remove)   MODE="remove"; NAME="$2"; shift 2 ;;
        *)         shift 1 ;;
    esac
done

# Sanitize the label (it feeds file names).
NAME=$(echo "$NAME" | tr -d '|/' | tr '[:space:]' '_' | tr -s '_' | sed 's/^_//; s/_$//')

mode_list() {
    mkdir -p "$SUBS_DIR"
    local f
    for f in "$SUBS_DIR"/*.conf; do
        [[ -f "$f" ]] || continue
        source "$f"
        echo -e "$NAME\t$URL\t-> https://${DOMAIN}/${SECRET}\trefresh: ${INTERVAL}h"
    done
}

mode_remove() {
    [[ -n "$NAME" ]] || { msg_err "Use: x-ui-sub-dub.sh -remove <name>"; exit 1; }
    local conf="$SUBS_DIR/${NAME}.conf" script="/usr/local/bin/xui-sub-${NAME}.sh"
    if [[ ! -f "$conf" ]]; then
        msg_err "No duplicated subscription named '$NAME' (see -list)."
        exit 1
    fi
    source "$conf"
    crontab -l 2>/dev/null | grep -v "xui-sub-${NAME}.sh" | crontab -
    rm -f "$script" "$conf" "$WEB_ROOT/$SECRET"
    msg_ok "Subscription '$NAME' removed (cron + file + config)."
}

# Validate a fetched subscription body: either base64 raw share links or JSON.
validate_sub() { # <file> -> 0 if looks like a subscription
    local f="$1"
    if base64 -d "$f" 2>/dev/null | grep -qE "^(vless|vmess|trojan|ss|tuic|hysteria2?|mtproto)://"; then
        return 0
    fi
    if head -c1 "$f" | grep -q '['; then
        python3 -c "import json,sys; json.load(open('$f'))" 2>/dev/null && return 0
    fi
    return 1
}

mode_add() {
    [[ -n "$URL" && -n "$NAME" ]] || { msg_err "Use: x-ui-sub-dub.sh -url <URL> -name <label>"; exit 1; }
    mkdir -p "$SUBS_DIR"

    # A fresh secret path that does not exist in the web root yet.
    local secret=""
    while :; do
        secret="x$(head -c 12 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 12)"
        [[ -e "$WEB_ROOT/$secret" ]] || break
    done

    msg_inf "Fetching $URL (client UA)..."
    local tmp out
    tmp=$(mktemp)
    # Some providers only serve real VPN clients — try common client UAs.
    for ua in "sing-box/1.9.0" "Clash/v1.18.0" "v2rayNG/1.8.19" "Happ"; do
        if curl -fsSL --max-time 30 -A "$ua" "$URL" -o "$tmp" && validate_sub "$tmp"; then
            break
        fi
        rm -f "$tmp"; tmp=$(mktemp)
    done
    if ! validate_sub "$tmp"; then
        rm -f "$tmp"
        msg_err "The remote subscription did not pass validation (unreachable, or not raw/JSON share links)."
        exit 1
    fi
    chmod 644 "$tmp"
    out="$WEB_ROOT/$secret"
    mv "$tmp" "$out"

    # Refresh script: re-fetch + re-validate, keep the previous copy on failure.
    local script="/usr/local/bin/xui-sub-${NAME}.sh"
    cat > "$script" <<EOF
#!/bin/bash
# Auto-generated by x-ui-sub-dub.sh (${NAME}) — do not edit.
URL='${URL}'
OUT='${out}'
tmp=\$(mktemp)
for ua in "sing-box/1.9.0" "Clash/v1.18.0" "v2rayNG/1.8.19" "Happ"; do
    if curl -fsSL --max-time 30 -A "\$ua" "\$URL" -o "\$tmp" \
       && (base64 -d "\$tmp" 2>/dev/null | grep -qE "^(vless|vmess|trojan|ss|tuic|hysteria2?|mtproto)://" \
           || head -c1 "\$tmp" | grep -q '\\['); then
        chmod 644 "\$tmp" && mv "\$tmp" "\$OUT" && break
    fi
    rm -f "\$tmp"; tmp=\$(mktemp)
done
rm -f "\$tmp"
EOF
    chmod +x "$script"

    local interval="${INTERVAL:-4}"
    crontab -l 2>/dev/null | grep -v "xui-sub-${NAME}.sh" | crontab -
    local minute=$((RANDOM % 60))
    (crontab -l 2>/dev/null; echo "${minute} */${interval} * * * ${script} >/dev/null 2>&1") | crontab -

    cat > "$SUBS_DIR/${NAME}.conf" <<EOF
NAME='${NAME}'
URL='${URL}'
SECRET='${secret}'
INTERVAL='${interval}'
EOF
    msg_ok "Duplicated subscription '${NAME}' is live:"
    echo
    echo "  https://${DOMAIN}/${secret}"
    echo
    msg_inf "Refreshed every ${interval} hours (cron); remove with: x-ui-sub-dub.sh -remove ${NAME}"
}

case "$MODE" in
    list)   mode_list ;;
    remove) mode_remove ;;
    add)    mode_add ;;
esac